version: "2"

services:
  webserver:
    image: nginx
    container_name: webserver1
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php:
    user: "www-data:www-data"
    build: .
    working_dir: /var/www
    command: php-fpm
    volumes:
      - ./:/var/www
    depends_on:
      - db
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql1
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_db
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  memcached:
    image: memcached:1.6-alpine
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
